# Site settings
title: Phil Crumm
email: pkcrumm@gmail.com
description: "Director of Strtegic Opportunities @10up, alum @pogoseat, @automattic, UCLA, pilot, and more."
baseurl: ""
url: "http://philcrumm.com"

# Build settings
markdown: kramdown

# Other configuration
permalink: /article/:title
